/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComparativaRouteImport } from './routes/comparativa'
import { Route as ControlRouteImport } from './routes/control'
import { Route as DatosRouteImport } from './routes/datos'
import { Route as EvolucionRouteImport } from './routes/evolucion'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as InformesRouteImport } from './routes/informes'
import { Route as PesajesRouteImport } from './routes/pesajes'
import { Route as PlantelRouteImport } from './routes/plantel'
import { Route as JugadorasIndexRouteImport } from './routes/jugadoras.index'
import { Route as JugadorasIdRouteImport } from './routes/jugadoras.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativaRoute = ComparativaRouteImport.update({
  id: '/comparativa',
  path: '/comparativa',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const DatosRoute = DatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucionRoute = EvolucionRouteImport.update({
  id: '/evolucion',
  path: '/evolucion',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const InformesRoute = InformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => rootRouteImport,
} as any)
const PesajesRoute = PesajesRouteImport.update({
  id: '/pesajes',
  path: '/pesajes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantelRoute = PlantelRouteImport.update({
  id: '/plantel',
  path: '/plantel',
  getParentRoute: () => rootRouteImport,
} as any)
const JugadorasIndexRoute = JugadorasIndexRouteImport.update({
  id: '/jugadoras/',
  path: '/jugadoras/',
  getParentRoute: () => rootRouteImport,
} as any)
const JugadorasIdRoute = JugadorasIdRouteImport.update({
  id: '/jugadoras/$id',
  path: '/jugadoras/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparativa': typeof ComparativaRoute
  '/control': typeof ControlRoute
  '/datos': typeof DatosRoute
  '/evolucion': typeof EvolucionRoute
  '/historial': typeof HistorialRoute
  '/informes': typeof InformesRoute
  '/pesajes': typeof PesajesRoute
  '/plantel': typeof PlantelRoute
  '/jugadoras/$id': typeof JugadorasIdRoute
  '/jugadoras/': typeof JugadorasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparativa': typeof ComparativaRoute
  '/control': typeof ControlRoute
  '/datos': typeof DatosRoute
  '/evolucion': typeof EvolucionRoute
  '/historial': typeof HistorialRoute
  '/informes': typeof InformesRoute
  '/pesajes': typeof PesajesRoute
  '/plantel': typeof PlantelRoute
  '/jugadoras/$id': typeof JugadorasIdRoute
  '/jugadoras': typeof JugadorasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparativa': typeof ComparativaRoute
  '/control': typeof ControlRoute
  '/datos': typeof DatosRoute
  '/evolucion': typeof EvolucionRoute
  '/historial': typeof HistorialRoute
  '/informes': typeof InformesRoute
  '/pesajes': typeof PesajesRoute
  '/plantel': typeof PlantelRoute
  '/jugadoras/$id': typeof JugadorasIdRoute
  '/jugadoras/': typeof JugadorasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparativa'
    | '/control'
    | '/datos'
    | '/evolucion'
    | '/historial'
    | '/informes'
    | '/pesajes'
    | '/plantel'
    | '/jugadoras/$id'
    | '/jugadoras/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comparativa'
    | '/control'
    | '/datos'
    | '/evolucion'
    | '/historial'
    | '/informes'
    | '/pesajes'
    | '/plantel'
    | '/jugadoras/$id'
    | '/jugadoras'
  id:
    | '__root__'
    | '/'
    | '/comparativa'
    | '/control'
    | '/datos'
    | '/evolucion'
    | '/historial'
    | '/informes'
    | '/pesajes'
    | '/plantel'
    | '/jugadoras/$id'
    | '/jugadoras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparativaRoute: typeof ComparativaRoute
  ControlRoute: typeof ControlRoute
  DatosRoute: typeof DatosRoute
  EvolucionRoute: typeof EvolucionRoute
  HistorialRoute: typeof HistorialRoute
  InformesRoute: typeof InformesRoute
  PesajesRoute: typeof PesajesRoute
  PlantelRoute: typeof PlantelRoute
  JugadorasIdRoute: typeof JugadorasIdRoute
  JugadorasIndexRoute: typeof JugadorasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativa': {
      id: '/comparativa'
      path: '/comparativa'
      fullPath: '/comparativa'
      preLoaderRoute: typeof ComparativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datos': {
      id: '/datos'
      path: '/datos'
      fullPath: '/datos'
      preLoaderRoute: typeof DatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucion': {
      id: '/evolucion'
      path: '/evolucion'
      fullPath: '/evolucion'
      preLoaderRoute: typeof EvolucionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informes': {
      id: '/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof InformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesajes': {
      id: '/pesajes'
      path: '/pesajes'
      fullPath: '/pesajes'
      preLoaderRoute: typeof PesajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantel': {
      id: '/plantel'
      path: '/plantel'
      fullPath: '/plantel'
      preLoaderRoute: typeof PlantelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jugadoras/': {
      id: '/jugadoras/'
      path: '/jugadoras'
      fullPath: '/jugadoras/'
      preLoaderRoute: typeof JugadorasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jugadoras/$id': {
      id: '/jugadoras/$id'
      path: '/jugadoras/$id'
      fullPath: '/jugadoras/$id'
      preLoaderRoute: typeof JugadorasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparativaRoute: ComparativaRoute,
  ControlRoute: ControlRoute,
  DatosRoute: DatosRoute,
  EvolucionRoute: EvolucionRoute,
  HistorialRoute: HistorialRoute,
  InformesRoute: InformesRoute,
  PesajesRoute: PesajesRoute,
  PlantelRoute: PlantelRoute,
  JugadorasIdRoute: JugadorasIdRoute,
  JugadorasIndexRoute: JugadorasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
